defaults:
  - garment_tokenizer: regression_garment_tokenizer

_target_: data.datasets.dataset_garmentcodedata_token_qva.GarmentCodeDatasetQVA


root_dir: /miele/data/gcd/garmentcodedata
editing_dir: /miele/data/gcd/garmentcodedata_editing
caption_dir: /miele/data/gcd/long-caption-processed
# sampling_rate: [0,0,0,0,1]
editing_flip_prob: 0.5
sampling_rate: [0.3, 0.1, 0.1, 0.4, 0.1]
image_size: 1024
vision_tower: openai/clip-vit-large-patch14 
panel_classification: assets/data_configs/panel_classes_garmentcodedata.json
load_by_dataname: assets/data_configs/garmentcodedata_list.txt